### ISSUE TITLE
Instructions for Creating HTML in Linux

### ISSUE THREAD

**Issue by duplaja** [MistressSaeko/a-girls-life#1]
Creating HTML for Linux users:

Clone or download the repo, open terminal, then `cd` into the root folder for the download.

Make tweego_nix64 (or 32) executable with: `chmod +X devtools/tweeGo/tweego_nix64`

Generate HTML with `./devtools/tweeGo/tweego_nix64 -s "Init" -o "bin/A Girl's Life.html" "src"`

**Comment by MistressSaeko** [comment]
Added to the readme. Thanks!
